version: '3'
services:
  web:
    build: .
    volumes:
      - ./flaskproject:/app
    ports:
      - 5000:5000
    links:
      - db
    tty: true
    command: flask run --host 0.0.0.0 --port 5000

  db:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: mydb
      MYSQL_USER: user
      MYSQL_PASSWORD: pass
      TZ: 'Asia/Tokyo'
    volumes:
      - ./flaskproject/db:/var/lib/mysql
    command: mysqld --character-set-server=utf8mb4 --collation-server=utf8mb4_bin
    ports:
      - 3333:3306




